version: "3.8"
services:
  db:
    image: postgres:15
    container_name: project-postgres
    restart: unless-stopped
    env_file:
      - .env # local file with your creds
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
